### ISSUE TITLE
Play a demo on desktop - not showing on many browsers

### ISSUE THREAD

**Issue by willwade** [googlecreativelab/morse-learn#14]
<img width="487" alt="Screenshot 2019-12-21 at 14 18 21" src="https://user-images.githubusercontent.com/229352/71309184-dc1f7000-23fc-11ea-8261-7771f4120266.png">

The above is what shows when you start the game on Safari/Mac. But I don't see this option on Chrome/Win or Edge/Win or Firefox/Win. Needs to show this option on more browsers.

**Comment by willwade** [comment]
Nb fixed in our fork. https://github.com/acecentre/morse-learn

**Comment by TechKey12313** [comment]
Still see this:
![Uploading Screenshot 2023-12-14 9.07.23 AM.png…]()

**Comment by TechKey12313** [comment]
Doesn't work for me:
![Screenshot 2023-12-14 9 07 23 AM](https://github.com/googlecreativelab/morse-learn/assets/148394674/1774e2fe-b86a-4281-a33a-a29e2ba59f58)

**Comment by willwade** [comment]
In our fork @TechKey12313 ?

**Comment by TechKey12313** [comment]
nvm
